### ISSUE TITLE
feat: Weekly ronk meeting. 

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/ronkathon#106]
We want to host a weekly call open to all contributors to go over tackling new cryptographic primitives. I would like to have some feedback from the community on this, and if there are any specific topics that would be helpful to have covered and what dates work well.

**Comment by devloper** [comment]
RONK: The foundation for the most epic cryptography CTF (soon)

**Comment by Autoparallel** [comment]
We should probably close this or otherwise revisit

**Comment by Autoparallel** [comment]
Closing for now
