### ISSUE TITLE
Bounty: HMAC

### ISSUE THREAD

**Issue by Autoparallel** [pluto/ronkathon#109]
# Hash-based Message Authentication Code: HMAC-SHA256

[HMAC](https://en.wikipedia.org/wiki/HMAC) is a message authentication code that allows you to verify both, Data integrity and Authenticity, of a message. We currently have no tool like this in ronkathon. It involves using multiple primitives together.

**Requirements**
An implementation of HMAC-SHA256 using [ronkathon's SHA256 hash](https://github.com/pluto/ronkathon/blob/main/src/hashes/sha256.rs) satisfying:

- [ ] #146
- [ ] #145

**Resources**
- [Wikipedia overview](https://en.wikipedia.org/wiki/HMAC)
- [HMAC Generator/Tester](https://www.freeformatter.com/hmac-generator.html)
- [How HMAC Works Step By Step](https://medium.com/@short_sparrow/how-hmac-works-step-by-step-explanation-with-examples-f4aff5efb40e)
- [What is HMAC?](https://www.geeksforgeeks.org/what-is-hmachash-based-message-authentication-code/)

**Criteria**
The winner will be selected based on the following criteria, in this order:

- Thorough convincing that the implementation is completely correct. (Requirements at least met.)
Code clarity and quality. This means succinct code that is easy to follow, naming, minimal use of other resources (no outside crates, please), use of Rust’s type system for flexibility and security (e.g., compile time checks where possible). Optimizations are a bonus, but should be de-prioritized for clarity. (Bonus points: If you want to add in slick optimizations, please gate these behind a feature!)
- Documentation quality. Other modules in ronkathon have wonderful READMEs, Cargo docs, and inline comments where code itself is not clear enough. ronkathon is primarily an educational toolbox and playground. We prioritize clarity, readability, and our contributors’ ability to learn and grow over anything. Help us maintain this quality throughout!

**Comment by madschristensen99** [comment]
This feels like you are trying to get hackers to just do your company's work for you

**Comment by 0xJepsen** [comment]
We don't use any of this code in production and it's strictly a learning resource so i am not sure how the company benefits from this work other from collaborating and learning with community. As we are sponsoring the hackathon in zkmontreal we decided to offer financial bounties to help people learn about different cryptographic primitives!
