### ISSUE TITLE
ci: consider running `udeps` on a weekly basis

### ISSUE THREAD

**Issue by eightfilms** [pluto/ronkathon#129]
`udeps` dominates CI running time - in this [recent run](https://github.com/pluto/ronkathon/actions/runs/9840311685) for example, udeps took about 5mins while the next longest job (tests) took ~1min.

An alternative is running it on a weekly basis and creating an issue (automatically via actions) instead. `udeps` isn't super urgent to fix within a PR either way, and can be tackled when an issue is found, rather than on every CI run.

Another alternative is to use [`cargo-machete`](https://github.com/bnjbvr/cargo-machete) instead which cuts down CI time instead (but this tool may result in false positives)

**Comment by 0xJepsen** [comment]
Im for this!

**Comment by Autoparallel** [comment]
Good call!
