### ISSUE TITLE
feat: Modular Arithmetic Optimization

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/ronkathon#16]
I think there are two modular arithmetic optimizations that would be good to add to the `field.rs` component. 

- [ ] #17
- [ ] #18

While they each have there distinct applications and performance improvements, since this is a learning resource, i believe we should at some point add both of them and well document each. 

There is a pretty good resource on both these algorithms with slides from risc0 [here](https://www.youtube.com/watch?v=hUl8ZB6hpUM&t=2307s)

**Comment by lonerapier** [comment]
Yup @0xJepsen, will start on this

**Comment by 0xJepsen** [comment]
> Yup @0xJepsen, will start on this

There is an example of the montgomery optimization here: https://github.com/Plonky3/Plonky3/blob/main/baby-bear/src/baby_bear.rs, it does depend on the field size.
