### ISSUE TITLE
chore: Release-plz is not working correctly 

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/ronkathon#175]
Currently whenever a new change is merged into main release-plz opens a PR setting the version to 0.1.0

The desired behavior is that it will detect the version in the main branch and it's pr will bump the version to the next minor release and amend changes to the change log from the last time it was merged in.

**Comment by Autoparallel** [comment]
This isn't really unintended. The crate isn't released!! It can't find a version to compare against. We just need to release the crate.

**Comment by 0xJepsen** [comment]
That true but it should still be able to compare semver on main when the publish flag is set to false right?

**Comment by Autoparallel** [comment]
No, what will it semver against? Semver is a different check entirely than release-plz, though release-plz uses `cargo-semver` prior to releasing.
