### ISSUE TITLE
evaluation domain

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/ronkathon#29]

**Comment by 0xJepsen** [comment]
@lonerapier Can you give a little more information here? Did you just mean monomial and Lagrange poly evaluation?

**Comment by Autoparallel** [comment]
Can we add a description here or close this? I'm not sure what it means actually lol

**Comment by lonerapier** [comment]
Meant it as a trait that allows polynomial evaluations using FFT/IFFTs, similar to [arkworks'](https://github.com/arkworks-rs/algebra/blob/master/poly/src/domain/mod.rs#L30). might be overkill for our use case, so I think we can close this issue.
