### ISSUE TITLE
Frontend for circuits

### ISSUE THREAD

**Issue by lonerapier** [pluto/ronkathon#53]
Simple frontend to write circuits specific for PLONK.

## Resources

- [Plonkathon](https://github.com/0xPARC/plonkathon/blob/main/compiler/program.py)
- [halo2 frontend](https://github.com/privacy-scaling-explorations/halo2/tree/main/halo2_frontend/src): might be overkill, but for future and learning purpose

**Comment by lonerapier** [comment]
@0xJepsen planning to hack on this, assigning to myself

**Comment by 0xJepsen** [comment]
Colin and I spoke and I think it would be good if we didn't do any optimizations for this repo if we can help it for now. Just to make it easier to debug until we have some proofs working.

**Comment by lonerapier** [comment]
Agreed. Will keep in mind.

**Comment by Autoparallel** [comment]
@lonerapier I'm going to take a stab at a Rusty version of this given what you already have done. I won't do it to intercept your progress, by the way. I just need to walk through these steps myself :)
