### ISSUE TITLE
feat: Scalar field to the curve sub groups

### ISSUE THREAD

**Issue by 0xJepsen** [pluto/ronkathon#62]
The scaler field of the curve subgroups should be of order 17. So we should build a field of order 17 and add that associated type as the scalar field for the Curves.

Would be awesome to add scalar multiplication with this type too!

**Comment by lonerapier** [comment]
I was thinking of generalising our field struct on modulus and generator so that it's easier to bootstrap other fields in future. Is it overkill for our use case?

**Comment by Autoparallel** [comment]
> I was thinking of generalising our field struct on modulus and generator so that it's easier to bootstrap other fields in future. Is it overkill for our use case?

No that's a good idea! I'm gonna put up a PR that closes this one, but I'd be happy to see a PR that makes this more flexible.
